CREATE TABLE CUSTOMERS(
    CNO NUMBER(5) PRIMARY KEY,
    CNAME VARCHAR2(10) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL
);
-- DROP TABLE ORDERS;
CREATE TABLE ORDERS(
    ORDERNO NUMBER(10) PRIMARY KEY,
    ORDERDATE DATE DEFAULT SYSDATE NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CNO NUMBER(5) NOT NULL,
    CHECK (STATUS IN ('결제완료', '배송중', '배송완료')),
    FOREIGN KEY (CNO) REFERENCES CUSTOMERS(CNO)
);

CREATE TABLE PRODUCTS(
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR(20) NOT NULL,
    COST NUMBER(8) DEFAULT 0 NOT NULL,
    STOCK NUMBER(5) DEFAULT 0 NOT NULL
);

CREATE TABLE ORDERDETAIL(
    ORDERNO NUMBER(10),
    PNO NUMBER(5),
    QTY NUMBER(5),
    COST NUMBER(8),
    PRIMARY KEY(ORDERNO, PNO),
    FOREIGN KEY (ORDERNO) REFERENCES ORDERS(ORDERNO),
    FOREIGN KEY (PNO) REFERENCES PRODUCTS(PNO)
);

INSERT INTO PRODUCTS VALUES(1001, '삼양라면', 1000, 200);
INSERT INTO PRODUCTS VALUES(1002, '새우깡', 1500, 500);
INSERT INTO PRODUCTS VALUES(1003, '월드콘', 2000, 350);
INSERT INTO PRODUCTS VALUES(1004, '빼빼로', 2000, 700);
INSERT INTO PRODUCTS VALUES(1005, '코카콜라', 1800, 550);
INSERT INTO PRODUCTS VALUES(1006, '환타', 1600, 300);

INSERT INTO CUSTOMERS VALUES(101, '김철수', '서울 강남구', 'CSKIM@NASVER.COM','899-6666');
INSERT INTO CUSTOMERS VALUES(102, '이영희', '부산 서면', 'YHLEE@EMPAL.COM','355-8882');
INSERT INTO CUSTOMERS VALUES(103, '최진국', '제주 동광양', 'JKCHOI@GMAIL.COM','852-5764');
INSERT INTO CUSTOMERS VALUES(104, '강준호', '강릉 홍제동', 'JHKANG@HANMAIL.COM','559-7777');
INSERT INTO CUSTOMERS VALUES(105, '민병국', '대구 전민동', 'BGMIN@HOTMAIL.COM','559-8741');
INSERT INTO CUSTOMERS VALUES(106, '오민수', '광주 북구', 'MSOH@MICROSOFT.COM','542-9988');

SELECT *
FROM PRODUCTS;
SELECT *
FROM CUSTOMERS;